version: '3.3'

services:
  githubactionbuildtests:
    container_name: test
    #image: gcr.io/githubactionbuildtests
    image: ${DOCKER_REGISTRY-}githubactionbuildtests
    build:
      context: .
      dockerfile: GithubActionBuildTests/Dockerfile
    environment:
      - TestValues__Value1="i am on docker desctop"
