version: '3.4'

services:
  githubactionbuildtests:
    container_name: test
    image: ${DOCKER_REGISTRY-}githubactionbuildtests
    build:
      context: .
      dockerfile: GithubActionBuildTests/Dockerfile
